### ISSUE TITLE
Error message when installing qupath-extension-align-0.4.0.jar

### ISSUE THREAD

**Issue by samewinguf** [qupath/qupath-extension-align#9]
I am a new QuPATH user, using version 0.4.3. I am looking to align serial sections for multiplex immunofluorescence stains. 

I downloaded the "qupath-extension-align-0.4.0.jar" file from this page.  I followed the instructions on the following webpage to install the extension: https://qupath.readthedocs.io/en/0.4/docs/intro/extensions.html

I dragged the .jar file into the main QuPATH window and selected a user directory to store the extension in. However, it did not properly import. I closed QuPATH and reopened as recommended. The following error message came up (see attached photo). It seems that it is incompatible with my QuPATH version. I know the .jar file says 0.4.0 and my version is 0.4.3, but I assumed this extension would be compatible with all 0.4.x versions. Maybe this is the issue though?

I am very new to both QuPATH and coding in general, so am not sure where to start with troubleshooting.

Thanks!

<img width="785" alt="qupath-image-alignment-error-message" src="https://github.com/qupath/qupath-extension-align/assets/152624249/b7e238bf-987a-45d1-b5b1-7f0f9edaa1c2">

**Comment by petebankhead** [comment]
The versioning is confusing & we need to document it better, but can you try either
* Using the latest QuPath release (v0.5.0) + the extension (v0.4.0)
* Using QuPath v0.4.3 and [v0.3.0 of the extension](https://github.com/qupath/qupath-extension-align/releases)

**Comment by samewinguf** [comment]
Thanks Pete!  This is super helpful.  I just downloaded the v0.3.0 extension and it loaded in properly.  I appreciate the help!
